version: '3.1'
services:
  data_socketProject_db:
    image: mongo
    container_name: data_socketProject_db
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: secret
    volumes:
      - ./data_socketProject_db:/data/db