POST http://localhost:5000/login
Content-Type: application/json

{
  "username": "chanhlongdeptrai3@gmail.com",
  "password": "longdeptrai"
}

###
POST http://localhost:5000/signup
Content-Type: application/json

{
  "username": "chanhlongdeptrai3@gmail.com",
  "password": "longdeptrai"
}