POST http://localhost:5000/login
Content-Type: application/json

{
  "username": "chanhlongdeptrai6@gmail.com",
  "password": "longdeptrai"
}

###
POST http://localhost:5000/signup
Content-Type: application/json

{
  "username": "chanhlongdeptrai6@gmail.com",
  "password": "longdeptrai",
  "nameaccount": "chanhlong6"
}